phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username $USERNAME --password-stdin $PASSWORD
  build:
    commands:
      - echo Building Docker images...
      - docker build --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL -t $FRONTEND_ECR ./frontend
      - docker build -t $BACKEND_ECR ./backend
  post_build:
    commands:
      - echo Pushing Docker images...
      - docker push $FRONTEND_ECR
      - docker push $BACKEND_ECR
      - echo Creating build artifacts...
      - printf '{"frontend-image": "%s", "backend-image": "%s"}' $FRONTEND_ECR $BACKEND_ECR > build.json
artifacts:
  files:
    - build.json