phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR Public...
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - echo Building Docker images...
      - |
        docker build --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL \
        -t public.ecr.aws/$PUBLIC_FRONTEND_REPO ./frontend
      - docker build -t public.ecr.aws/$PUBLIC_BACKEND_REPO ./backend
  post_build:
    commands:
      - echo Pushing Docker images to ECR Public...
      - docker push public.ecr.aws/$PUBLIC_FRONTEND_REPO
      - docker push public.ecr.aws/$PUBLIC_BACKEND_REPO
      - |
        echo Creating build artifacts...
        printf '{"frontend-image": "%s", "backend-image": "%s"}' \
        public.ecr.aws/$PUBLIC_FRONTEND_REPO public.ecr.aws/$PUBLIC_BACKEND_REPO > build.json

artifacts:
  files:
    - build.json
