---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker (DockerHub) and ECR Public..."
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws

      - echo "Installing dependencies for the frontend..."
      - npm ci --prefix frontend

      - echo "Auditing frontend dependencies for vulnerabilities..."
      - npm audit --prefix frontend || true

  build:
    commands:
      - echo "Running Prettier for the frontend..."
      - npx prettier --write "frontend/src/**/*.{ts,tsx}"

      - echo "Running linting tests for the frontend..."
      - npm run lint --prefix frontend

      - echo "Building Docker image for the frontend..."
      - docker build --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL \
        -t public.ecr.aws/r9k7h7m9/frontend-repo:latest \
        ./frontend

  post_build:
    commands:
      - echo "Pushing the Docker image for the frontend to ECR Public..."
      - docker push public.ecr.aws/r9k7h7m9/frontend-repo:latest

      - echo "Creating imagedefinitions.json for the frontend..."
      - printf '[{"name":"FE-container","imageUri":"public.ecr.aws/r9k7h7m9/frontend-repo:latest"}]' \
        > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - /root/.npm
    - frontend/node_modules
