version: '3.8'

services:
  # Frontend Service
  frontend:
    image: frontend:prod
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app_network

  # Backend Service
  backend:
    image: backend:prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app_network

  # Load Balancer
  nginx:
    image: nginx:1.26.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
