services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PORT=${BACKEND_PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PORT: ${FRONTEND_PORT}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}

  video-host:
    build:
      context: ./video-host
      dockerfile: Dockerfile
      args:
        PORT: ${VIDEO_HOST_PORT}
    ports:
      - "${VIDEO_HOST_PORT}:${VIDEO_HOST_PORT}"
    environment:
      - PORT=${VIDEO_HOST_PORT}
