version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://finnbar:wUk54NprYsw4caJe@cluster0.ywien.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8081"  
    depends_on:
      - backend
