services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=[Insert your mongo URI here]
      - PORT=5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:5000/api
    container_name: frontend-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    depends_on:
      - backend
